const tagList: string[] = [
  'mmorpg', 'shooter', 'strategy', 'moba', 'racing', 'sports',
  'social', 'sandbox', 'survival', 'pvp', 'pve', 'pixel',
  'voxel', 'zombie', 'tank', 'space', 'sailing', 'superhero',
  'permadeath', 'card', 'mmo', 'mmofps', 'mmotps', '3d',
  '2d', 'anime', 'fantasy', 'fighting', 'action', 'military',
  'flight', 'horror', 'mmorts', 'low-spec', 'tower-defense',
  'open-world', 'martial-arts', 'turn-based', 'action-rpg',
  'sci-fi', 'battle-royale', 'first-person', 'third-Person',
  'top-down', 'side-scroller'
]

const platformList: string[] = ['browser', 'pc']

export { tagList, platformList }